# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "commit" {
  type    = string
  default = "0000000"
}

variable "cpus" {
  type    = string
  default = "4"
}

variable "disk_size" {
  type    = string
  default = "51200"
}

variable "display" {
  type    = string
  default = "gtk"
}

variable "driver_iso_dir" {
  type    = string
  default = "./packer_cache/virtio-win"
}

variable "gcp_project" {
  type    = string
  default = "${env("GCP_PROJECT")}"
}

variable "gcs_bucket" {
  type    = string
  default = "${env("GCS_BUCKET")}"
}

variable "gcp_account_file" {
  type    = string
  default = "${env("GCS_CREDS_FILE")}"
}

variable "headless" {
  type    = string
  default = "false"
}

variable "home" {
  type    = string
  default = "${env("HOME")}"
}

variable "iso_checksum" {
  type    = string
  default = "026607e7aa7ff80441045d8830556bf8899062ca9b3c543702f112dd6ffe6078"
}

variable "iso_url" {
  type    = string
  default = "${env("ISO_URL")}"
}

variable "memory" {
  type    = string
  default = "8192"
}

variable "image_family" {
  type    = string
  default = "windows"
}

variable "qemu_accelerator" {
  type    = string
  default = "kvm"
}

variable "version" {
  type    = string
  default = "0.0.1"
}

variable "windows_version" {
  type    = string
  default = "10"
}

variable "winrm_password" {
  type    = string
  default = "admin"
}

variable "winrm_username" {
  type    = string
  default = "admin"
}

## These are used by the build script but not packer. Adding here to avoid warnings.
variable "name" {
  type    = string
  default = ""
}

variable "sha256" {
  type    = string
  default = ""
}

variable "environment" {
  type    = string
  default = ""
}

variable "driver_iso_url" {
  type    = string
  default = ""
}

variable "driver_iso_sha256" {
  type    = string
  default = ""
}

variable "template" {
  type    = string
  default = ""
}




# "timestamp" template function replacement
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }
# The "legacy_isotime" function has been provided for backwards compatability, but we recommend switching to the timestamp and formatdate functions.

# All locals variables are generated from variables that uses expressions
# that are not allowed in HCL2 variables.
# Read the documentation for locals blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/locals
locals {
  autounattend = "installer-configs/windows-${var.windows_version}/Autounattend.xml"
  build_date   = "${legacy_isotime("20060102")}"
  build_number = "${legacy_isotime("20060102")}"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
# could not parse template for following block: "template: hcl2_upgrade:2: bad character U+0060 '`'"

source "qemu" "windows-iso" {
  accelerator  = var.qemu_accelerator
  boot_command = []
  boot_wait    = "6m"
  cd_files     = ["${var.driver_iso_dir}/*"]
  floppy_files = [
    local.autounattend,
    "./files/WindowsPowershell.lnk",
    "./files/PinTo10.exe",
    "./scripts/windows/fixnetwork.ps1",
    "./scripts/windows/rearm-windows.ps1",
    "./scripts/windows/disable-screensaver.ps1",
    "./scripts/windows/disable-winrm.ps1",
    "./scripts/windows/enable-winrm.ps1",
    "./scripts/windows/microsoft-updates.bat",
    "./scripts/windows/win-updates.ps1",
    "./scripts/windows/unattend.xml",
    "./scripts/windows/sysprep.bat"
  ]
  output_directory = "output/${var.image_family}-qemu-install"
  communicator     = "winrm"
  cpus             = var.cpus
  disk_cache       = "unsafe"
  disk_interface   = "virtio-scsi"
  disk_size        = var.disk_size
  display          = var.display
  format           = "raw"
  headless         = var.headless
  iso_checksum     = var.iso_checksum
  iso_urls         = [var.iso_url]
  memory           = var.memory
  net_device       = "virtio-net"
  shutdown_command = "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  shutdown_timeout = "2h"
  vm_name          = "disk.raw"
  winrm_password   = var.winrm_password
  winrm_timeout    = "12h"
  winrm_username   = var.winrm_username
}

build {
  name = "install"

  sources = ["source.qemu.windows-iso"]

  post-processor "checksum" {
    checksum_types      = ["sha1", "sha256"]
    output              = "output/${var.image_family}-${source.type}-install/disk.raw.{{.ChecksumType}}"
    keep_input_artifact = true
  }
}

source "qemu" "windows-base" {
  iso_url              = "output/${var.image_family}-qemu-install/disk.raw"
  iso_checksum         = "file:./output/${var.image_family}-qemu-install/disk.raw.sha256"
  iso_target_extension = "raw"
  disk_image           = true
  floppy_files = [
    "./scripts/windows/unattend.xml",
    "./scripts/windows/sysprep.bat"
  ]
  output_directory = "output/${var.image_family}-qemu-base"
  accelerator      = var.qemu_accelerator
  boot_command     = []
  # boot_wait        = "6m"
  communicator     = "winrm"
  cpus             = var.cpus
  disk_cache       = "unsafe"
  disk_interface   = "virtio-scsi"
  disk_size        = var.disk_size
  display          = var.display
  format           = "raw"
  headless         = var.headless
  memory           = var.memory
  net_device       = "virtio-net"
  shutdown_command = ""
  shutdown_timeout = "2h"
  vm_name          = "disk.raw"
  winrm_password   = var.winrm_password
  winrm_timeout    = "12h"
  winrm_username   = var.winrm_username
}

build {
  name = "base"

  sources = ["source.qemu.windows-base"]

  provisioner "ansible" {
    playbook_file = "./ansible/playbook.yml"
    use_proxy     = false
    extra_arguments = [
      "-e", "ansible_winrm_server_cert_validation=ignore",
      "-e", "ansible_winrm_scheme=http",
      "-e", "ansible_user=${var.winrm_username}"
    ]
  }

  provisioner "powershell" {
    debug_mode       = 1
    execution_policy = "unrestricted"
    scripts          = ["./scripts/windows/install-latest-powershell.ps1", "./scripts/windows/install-chocolatey.ps1", "./scripts/windows/gce-windows.ps1"]
  }


  provisioner "windows-shell" {
    execute_command = "{{ .Vars }} cmd /c \"{{ .Path }}\""
    remote_path     = "/tmp/script.bat"
    scripts         = ["./scripts/windows/enable-rdp.bat"]
  }

  provisioner "powershell" {
    scripts = ["./scripts/windows/configure-rdp.ps1", "./scripts/windows/debloat-windows.ps1"]
  }

  provisioner "windows-restart" {
    restart_timeout = "15m"
  }

  provisioner "powershell" {
    scripts = ["./scripts/windows/set-powerplan.ps1"]
  }

  provisioner "windows-shell" {
    execute_command = "{{ .Vars }} cmd /c \"{{ .Path }}\""
    remote_path     = "/tmp/script.bat"
    scripts         = ["./scripts/windows/pin-powershell.bat", "./scripts/windows/compile-dotnet-assemblies.bat", "./scripts/windows/set-winrm-automatic.bat", "./scripts/windows/dis-updates.bat"]
  }

  provisioner "powershell" {
    scripts = ["./scripts/windows/optimize-image.ps1", "./scripts/windows/run-sysprep.ps1"]
  }

  post-processor "checksum" {
    checksum_types      = ["sha1", "sha256"]
    output              = "output/${var.image_family}-${source.type}-base/disk.raw.{{.ChecksumType}}"
    keep_input_artifact = true
  }

  post-processors {
    post-processor "compress" {
      name   = "gcp-import"
      output = "output/${var.image_family}_${source.type}_base.tar.gz"
    }
    post-processor "googlecompute-import" {
      account_file            = "${var.gcp_account_file}"
      bucket                  = "${var.gcs_bucket}"
      project_id              = "${var.gcp_project}"
      image_description       = "Microsoft, Windows ${var.windows_version}, built on ${local.build_date} with Packer."
      image_family            = var.image_family
      image_guest_os_features = ["WINDOWS", "MULTI_IP_SUBNET", "VIRTIO_SCSI_MULTIQUEUE"]
      image_labels = {
        build_number = "${local.build_number}"
        buildstamp   = "${local.timestamp}"
        commit       = "${var.commit}"
      }
      image_name = "${var.image_family}-${local.build_date}"
    }
  }
}
