- hosts: all
  vars:
    bleachbit_url: https://download.bleachbit.org/BleachBit-4.4.0-portable.zip
    install_updates: False
  tasks:
    - name: Harden and Activate RDP
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        value: "{{ item.value }}"
        data: "{{ item.data }}"
        datatype: dword
      loop:
        - {value: "MinEncryptionLevel", data: 3} # Set encryption to High
        - {value: "UserAuthentication", data: 1} # Require network auth
        - {value: "SecurityLayer",      data: 2} # Require TLS
        - {value: "fDenyTSConnections", data: 0} # Allow RDP

    - name: Disable Ctrl + Alt + Del
      win_regedit:
        key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
        value: "DisableCAD"
        data: 1
        datatype: dword

    - name: Use the plaintext WinRM transport and force it to use basic authentication
      win_shell: winrm set winrm/config/service '@{AllowUnencrypted="true"}'

    - name: Enable Firewall Inbound Rules Group
      win_shell: Enable-NetFirewallRule -DisplayGroup "{{ item }}"
      loop:
        - Remote Desktop
        - Windows Remote Management

    # Install choco package
    - name: Install chocolatey and packages
      win_chocolatey:
        name:
        - vscode

    - name: Install OpenSSH Server for Windows
      win_feature:
        name:
        - OpenSSH.Server
        state: present

    - name: Enable OpenSSH Server on Startup
      win_service:
        name: sshd
        start_mode: auto
        start: started

    - name: Configure Explorer settings
      win_regedit:
        key: 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\'
        value: "{{ item.value }}"
        data: "{{ item.data }}"
        datatype: dword
      loop:
        - {value: "HideFileExt", data: 0} # Show file extensions
        - {value: "Start_ShowRun", data: 1} # Show run in start menu
        - {value: "StartMenuAdminTools", data: 1} # Show Admin Tools in Start Menu

    - name: Disable Hibernation mode
      win_regedit:
        key: 'HKLM:\SYSTEM\CurrentControlSet\Control\Power'
        value: "{{ item.value }}"
        data: "{{ item.data }}"
        datatype: dword
      loop:
        - {value: "HibernateFileSizePercent", data: 0} # Zero Hibernation File
        - {value: "HibernateEnabled", data: 1} # Disable Hibernation Mode
      when: ansible_distribution is search("Microsoft Windows 10")

    - name: Set ultimate performance mode
      win_regedit:
        key: 'HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings'
        value: "ActivePowerScheme"
        data: "e9a42b02-d5df-448d-aa00-03f14749eb61" # Enable Ultimate Performance plan
        datatype: string
      when: ansible_distribution is search("Microsoft Windows 10")


    - name: Enable AutoLogon
      win_regedit:
        key: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
        value: "DefaultPassword"
        data: "admin"
        datatype: string

    - name: Disable password expiration for admin user
      win_shell: wmic useraccount where "name='admin'" set PasswordExpires=FALSE

    - name: Remove all current pagefiles
      win_pagefile:
        remove_all: yes
        automatic: no
        state: absent

    - name: Disable Hibernate Mode
      win_command: powercfg -h off
      changed_when: false
      when: ansible_distribution is search("Microsoft Windows 10")

    - name: Install windows updates
      win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        reboot: yes
        reboot_timeout: 10000
      register: windows_updates
      when: install_updates

    - name: Windows reboot
      win_reboot:
        reboot_timeout: 10000
      when: install_updates and windows_updates.reboot_required and allow_windows_reboot_during_win_updates
